COMMENT: 'Training on Stanford2D-3D(train)+PanoContext(whole)'
TAG: 's2d3d'
SEED: 123
MODEL:
  NAME: 'LGT_Net'
  ARGS: [ {
    'decoder_name': 'SWG_Transformer',
    'win_size': 16,
    'rpe': 'lr_parameter_mirror',
    'dropout': 0.0,
    'depth': 6,
    'output_name': 'LGT'
  } ]
TRAIN:
  DEVICE: 'cuda:2'
  SCRATCH: False
  DETERMINISTIC: True
  CRITERION:
    DEPTH:
      WEIGHT: 0.9
    RATIO:
      WEIGHT: 0.1
    GRAD:
      WEIGHT: 0.1
      WEIGHTS: [ 1.0, 1.0 ]
  BASE_LR:
    1e-4
  RESUME_LAST: False
  OPTIMIZER:
    NAME: 'adam'
  EPOCHS: 1000
DATA:
  DATASET: 'pano_s2d3d_mix'
  DIR: 'src/dataset/pano_s2d3d'
  SUBSET: 's2d3d'
  BATCH_SIZE: 6
  NUM_WORKERS: 6
  FOR_TEST_INDEX: None
  AUG:
    FLIP: True
    STRETCH: True
    ROTATE: True
    GAMMA: True
AMP_OPT_LEVEL: 'O0'
